#!/bin/bash
#PBS -S /bin/bash
#PBS -o /home/tnguye46/bayesian_itc_reproduce/ubtln36/2.bitc_mcmc/repeat_0/ubtln36b/ubtln36b_mcmc.log 
#PBS -j oe
#PBS -l nodes=1:ppn=1,mem=2048mb,walltime=72:00:00

source /home/tnguye46/opt/module/anaconda.sh
cd /home/tnguye46/bayesian_itc_reproduce/ubtln36/2.bitc_mcmc/repeat_0/ubtln36b
date
python /home/tnguye46/opt/src/bayesian-itc/scripts/bitc_mcmc.py twocomponent /home/tnguye46/bayesian_itc_reproduce/ubtln36/1.itc_origin_heat_files/ubtln36b.itc /home/tnguye46/bayesian_itc_reproduce/ubtln36/1.itc_origin_heat_files/ubtln36b.TXT --dc 0.100000  --ds 0.100000  --dummy_itc_file  --niters 11000000  --nburn 1000000  --nthin 2000 -v
date 
