#!/bin/bash
#PBS -S /bin/bash
#PBS -o /home/tnguye46/bayesian_itc/Mg2EDTA/2.bitc_mcmc_lognomP0_lognomLs/repeat_0/Mg1EDTAp1d/Mg1EDTAp1d_mcmc.log 
#PBS -j oe
#PBS -l nodes=1:ppn=1,mem=2048mb,walltime=72:00:00

source /home/tnguye46/opt/module/anaconda.sh
cd /home/tnguye46/bayesian_itc/Mg2EDTA/2.bitc_mcmc_lognomP0_lognomLs/repeat_0/Mg1EDTAp1d
date
python /home/tnguye46/opt/src/bayesian-itc/scripts/bitc_mcmc.py twocomponent /home/tnguye46/bayesian_itc/Mg2EDTA/1.itc_origin_heat_files/Mg1EDTAp1d.itc /home/tnguye46/bayesian_itc/Mg2EDTA/1.itc_origin_heat_files/Mg1EDTAp1d.DAT --dc 0.100000  --ds 0.100000     --concentration_range_factor 10.000000  --niters 11000000  --nburn 1000000  --nthin 2000 -vvv
date 
