#!/bin/bash
#PBS -S /bin/bash
#PBS -o /home/tnguye46/bayesian_itc_reproduce/ABRF_MIRG02/5.bitc_mcmc_uniform_prior_4_cell_concen/repeat_0/1_MCS-ITC/1_MCS-ITC_mcmc.log 
#PBS -j oe
#PBS -l nodes=1:ppn=1,mem=2048mb,walltime=72:00:00

source /home/tnguye46/opt/module/anaconda.sh
cd /home/tnguye46/bayesian_itc_reproduce/ABRF_MIRG02/5.bitc_mcmc_uniform_prior_4_cell_concen/repeat_0/1_MCS-ITC
date
python /home/tnguye46/opt/src/bayesian-itc/scripts/bitc_mcmc.py twocomponent /home/tnguye46/bayesian_itc_reproduce/ABRF_MIRG02/3.dummy_itc_files/1_MCS-ITC.itc /home/tnguye46/bayesian_itc_reproduce/ABRF_MIRG02/4.heat_in_origin_format/1_MCS-ITC.DAT --dc 0.100000  --ds 0.001000  --dummy_itc_file  --uniform_cell_concentration   --concentration_range_factor 100.000000  --niters 11000000  --nburn 1000000  --nthin 2000 -vvv
date 
