#!/bin/bash
#PBS -S /bin/bash
#PBS -o /home/tnguye46/bayesian_itc/ubtln59/2.bitc_mcmc_unifP0_sharplognomLs/repeat_0/ubtln59b/ubtln59b_mcmc.log 
#PBS -j oe
#PBS -l nodes=1:ppn=1,mem=2048mb,walltime=72:00:00

source /home/tnguye46/opt/module/anaconda.sh
cd /home/tnguye46/bayesian_itc/ubtln59/2.bitc_mcmc_unifP0_sharplognomLs/repeat_0/ubtln59b
date
python /home/tnguye46/opt/src/bayesian-itc/scripts/bitc_mcmc.py twocomponent /home/tnguye46/bayesian_itc/ubtln59/1.itc_origin_heat_files/ubtln59b.itc /home/tnguye46/bayesian_itc/ubtln59/1.itc_origin_heat_files/ubtln59b.TXT --dc 0.100000  --ds 0.001000  --dummy_itc_file  --uniform_cell_concentration   --concentration_range_factor 10.000000  --niters 11000000  --nburn 1000000  --nthin 2000 -vvv
date 
