#!/bin/bash
#PBS -S /bin/bash
#PBS -o /home/tnguye46/bayesian_itc_reproduce/ubtln59/2.bitc_mcmc/repeat_1/ubtln59neuesProtein/ubtln59neuesProtein_mcmc.log 
#PBS -j oe
#PBS -l nodes=1:ppn=1,mem=2048mb,walltime=72:00:00

source /home/tnguye46/opt/module/anaconda.sh
cd /home/tnguye46/bayesian_itc_reproduce/ubtln59/2.bitc_mcmc/repeat_1/ubtln59neuesProtein
date
python /home/tnguye46/opt/src/bayesian-itc/scripts/bitc_mcmc.py twocomponent /home/tnguye46/bayesian_itc_reproduce/ubtln59/1.itc_origin_heat_files/ubtln59neuesProtein.itc /home/tnguye46/bayesian_itc_reproduce/ubtln59/1.itc_origin_heat_files/ubtln59neuesProtein.TXT --dc 0.100000  --ds 0.100000  --dummy_itc_file  --niters 11000000  --nburn 1000000  --nthin 2000 -v
date 
